/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StwOperationsXpboostsRouteRouteImport } from './routes/stw-operations/xpboosts/route'
import { Route as StwOperationsUrnsRouteRouteImport } from './routes/stw-operations/urns/route'
import { Route as StwOperationsTaxiServiceRouteRouteImport } from './routes/stw-operations/taxi-service/route'
import { Route as StwOperationsPartyRouteRouteImport } from './routes/stw-operations/party/route'
import { Route as StwOperationsDailyQuestsRouteRouteImport } from './routes/stw-operations/daily-quests/route'
import { Route as StwOperationsAutomationRouteRouteImport } from './routes/stw-operations/automation/route'
import { Route as StwOperationsAutoLlamasRouteRouteImport } from './routes/stw-operations/auto-llamas/route'
import { Route as InformationCreditsRouteRouteImport } from './routes/information/credits/route'
import { Route as AdvancedModeWorldInfoRouteRouteImport } from './routes/advanced-mode/world-info/route'
import { Route as AdvancedModeMatchmakingTrackRouteRouteImport } from './routes/advanced-mode/matchmaking-track/route'
import { Route as AccountsRemoveRouteRouteImport } from './routes/accounts/remove/route'
import { Route as AccountManagementVbucksInformationRouteRouteImport } from './routes/account-management/vbucks-information/route'
import { Route as AccountManagementRedeemCodesRouteRouteImport } from './routes/account-management/redeem-codes/route'
import { Route as AccountManagementEulaRouteRouteImport } from './routes/account-management/eula/route'
import { Route as AccountManagementEpicGamesSettingsRouteRouteImport } from './routes/account-management/epic-games-settings/route'
import { Route as AccountManagementDevicesAuthRouteRouteImport } from './routes/account-management/devices-auth/route'
import { Route as AccountsAddTypeRouteImport } from './routes/accounts/add/$type'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StwOperationsXpboostsRouteRoute =
  StwOperationsXpboostsRouteRouteImport.update({
    id: '/stw-operations/xpboosts',
    path: '/stw-operations/xpboosts',
    getParentRoute: () => rootRouteImport,
  } as any)
const StwOperationsUrnsRouteRoute = StwOperationsUrnsRouteRouteImport.update({
  id: '/stw-operations/urns',
  path: '/stw-operations/urns',
  getParentRoute: () => rootRouteImport,
} as any)
const StwOperationsTaxiServiceRouteRoute =
  StwOperationsTaxiServiceRouteRouteImport.update({
    id: '/stw-operations/taxi-service',
    path: '/stw-operations/taxi-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const StwOperationsPartyRouteRoute = StwOperationsPartyRouteRouteImport.update({
  id: '/stw-operations/party',
  path: '/stw-operations/party',
  getParentRoute: () => rootRouteImport,
} as any)
const StwOperationsDailyQuestsRouteRoute =
  StwOperationsDailyQuestsRouteRouteImport.update({
    id: '/stw-operations/daily-quests',
    path: '/stw-operations/daily-quests',
    getParentRoute: () => rootRouteImport,
  } as any)
const StwOperationsAutomationRouteRoute =
  StwOperationsAutomationRouteRouteImport.update({
    id: '/stw-operations/automation',
    path: '/stw-operations/automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const StwOperationsAutoLlamasRouteRoute =
  StwOperationsAutoLlamasRouteRouteImport.update({
    id: '/stw-operations/auto-llamas',
    path: '/stw-operations/auto-llamas',
    getParentRoute: () => rootRouteImport,
  } as any)
const InformationCreditsRouteRoute = InformationCreditsRouteRouteImport.update({
  id: '/information/credits',
  path: '/information/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedModeWorldInfoRouteRoute =
  AdvancedModeWorldInfoRouteRouteImport.update({
    id: '/advanced-mode/world-info',
    path: '/advanced-mode/world-info',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdvancedModeMatchmakingTrackRouteRoute =
  AdvancedModeMatchmakingTrackRouteRouteImport.update({
    id: '/advanced-mode/matchmaking-track',
    path: '/advanced-mode/matchmaking-track',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsRemoveRouteRoute = AccountsRemoveRouteRouteImport.update({
  id: '/accounts/remove',
  path: '/accounts/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountManagementVbucksInformationRouteRoute =
  AccountManagementVbucksInformationRouteRouteImport.update({
    id: '/account-management/vbucks-information',
    path: '/account-management/vbucks-information',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountManagementRedeemCodesRouteRoute =
  AccountManagementRedeemCodesRouteRouteImport.update({
    id: '/account-management/redeem-codes',
    path: '/account-management/redeem-codes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountManagementEulaRouteRoute =
  AccountManagementEulaRouteRouteImport.update({
    id: '/account-management/eula',
    path: '/account-management/eula',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountManagementEpicGamesSettingsRouteRoute =
  AccountManagementEpicGamesSettingsRouteRouteImport.update({
    id: '/account-management/epic-games-settings',
    path: '/account-management/epic-games-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountManagementDevicesAuthRouteRoute =
  AccountManagementDevicesAuthRouteRouteImport.update({
    id: '/account-management/devices-auth',
    path: '/account-management/devices-auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const AccountsAddTypeRoute = AccountsAddTypeRouteImport.update({
  id: '/accounts/add/$type',
  path: '/accounts/add/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/account-management/devices-auth': typeof AccountManagementDevicesAuthRouteRoute
  '/account-management/epic-games-settings': typeof AccountManagementEpicGamesSettingsRouteRoute
  '/account-management/eula': typeof AccountManagementEulaRouteRoute
  '/account-management/redeem-codes': typeof AccountManagementRedeemCodesRouteRoute
  '/account-management/vbucks-information': typeof AccountManagementVbucksInformationRouteRoute
  '/accounts/remove': typeof AccountsRemoveRouteRoute
  '/advanced-mode/matchmaking-track': typeof AdvancedModeMatchmakingTrackRouteRoute
  '/advanced-mode/world-info': typeof AdvancedModeWorldInfoRouteRoute
  '/information/credits': typeof InformationCreditsRouteRoute
  '/stw-operations/auto-llamas': typeof StwOperationsAutoLlamasRouteRoute
  '/stw-operations/automation': typeof StwOperationsAutomationRouteRoute
  '/stw-operations/daily-quests': typeof StwOperationsDailyQuestsRouteRoute
  '/stw-operations/party': typeof StwOperationsPartyRouteRoute
  '/stw-operations/taxi-service': typeof StwOperationsTaxiServiceRouteRoute
  '/stw-operations/urns': typeof StwOperationsUrnsRouteRoute
  '/stw-operations/xpboosts': typeof StwOperationsXpboostsRouteRoute
  '/accounts/add/$type': typeof AccountsAddTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/account-management/devices-auth': typeof AccountManagementDevicesAuthRouteRoute
  '/account-management/epic-games-settings': typeof AccountManagementEpicGamesSettingsRouteRoute
  '/account-management/eula': typeof AccountManagementEulaRouteRoute
  '/account-management/redeem-codes': typeof AccountManagementRedeemCodesRouteRoute
  '/account-management/vbucks-information': typeof AccountManagementVbucksInformationRouteRoute
  '/accounts/remove': typeof AccountsRemoveRouteRoute
  '/advanced-mode/matchmaking-track': typeof AdvancedModeMatchmakingTrackRouteRoute
  '/advanced-mode/world-info': typeof AdvancedModeWorldInfoRouteRoute
  '/information/credits': typeof InformationCreditsRouteRoute
  '/stw-operations/auto-llamas': typeof StwOperationsAutoLlamasRouteRoute
  '/stw-operations/automation': typeof StwOperationsAutomationRouteRoute
  '/stw-operations/daily-quests': typeof StwOperationsDailyQuestsRouteRoute
  '/stw-operations/party': typeof StwOperationsPartyRouteRoute
  '/stw-operations/taxi-service': typeof StwOperationsTaxiServiceRouteRoute
  '/stw-operations/urns': typeof StwOperationsUrnsRouteRoute
  '/stw-operations/xpboosts': typeof StwOperationsXpboostsRouteRoute
  '/accounts/add/$type': typeof AccountsAddTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRoute
  '/account-management/devices-auth': typeof AccountManagementDevicesAuthRouteRoute
  '/account-management/epic-games-settings': typeof AccountManagementEpicGamesSettingsRouteRoute
  '/account-management/eula': typeof AccountManagementEulaRouteRoute
  '/account-management/redeem-codes': typeof AccountManagementRedeemCodesRouteRoute
  '/account-management/vbucks-information': typeof AccountManagementVbucksInformationRouteRoute
  '/accounts/remove': typeof AccountsRemoveRouteRoute
  '/advanced-mode/matchmaking-track': typeof AdvancedModeMatchmakingTrackRouteRoute
  '/advanced-mode/world-info': typeof AdvancedModeWorldInfoRouteRoute
  '/information/credits': typeof InformationCreditsRouteRoute
  '/stw-operations/auto-llamas': typeof StwOperationsAutoLlamasRouteRoute
  '/stw-operations/automation': typeof StwOperationsAutomationRouteRoute
  '/stw-operations/daily-quests': typeof StwOperationsDailyQuestsRouteRoute
  '/stw-operations/party': typeof StwOperationsPartyRouteRoute
  '/stw-operations/taxi-service': typeof StwOperationsTaxiServiceRouteRoute
  '/stw-operations/urns': typeof StwOperationsUrnsRouteRoute
  '/stw-operations/xpboosts': typeof StwOperationsXpboostsRouteRoute
  '/accounts/add/$type': typeof AccountsAddTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/account-management/devices-auth'
    | '/account-management/epic-games-settings'
    | '/account-management/eula'
    | '/account-management/redeem-codes'
    | '/account-management/vbucks-information'
    | '/accounts/remove'
    | '/advanced-mode/matchmaking-track'
    | '/advanced-mode/world-info'
    | '/information/credits'
    | '/stw-operations/auto-llamas'
    | '/stw-operations/automation'
    | '/stw-operations/daily-quests'
    | '/stw-operations/party'
    | '/stw-operations/taxi-service'
    | '/stw-operations/urns'
    | '/stw-operations/xpboosts'
    | '/accounts/add/$type'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/account-management/devices-auth'
    | '/account-management/epic-games-settings'
    | '/account-management/eula'
    | '/account-management/redeem-codes'
    | '/account-management/vbucks-information'
    | '/accounts/remove'
    | '/advanced-mode/matchmaking-track'
    | '/advanced-mode/world-info'
    | '/information/credits'
    | '/stw-operations/auto-llamas'
    | '/stw-operations/automation'
    | '/stw-operations/daily-quests'
    | '/stw-operations/party'
    | '/stw-operations/taxi-service'
    | '/stw-operations/urns'
    | '/stw-operations/xpboosts'
    | '/accounts/add/$type'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/account-management/devices-auth'
    | '/account-management/epic-games-settings'
    | '/account-management/eula'
    | '/account-management/redeem-codes'
    | '/account-management/vbucks-information'
    | '/accounts/remove'
    | '/advanced-mode/matchmaking-track'
    | '/advanced-mode/world-info'
    | '/information/credits'
    | '/stw-operations/auto-llamas'
    | '/stw-operations/automation'
    | '/stw-operations/daily-quests'
    | '/stw-operations/party'
    | '/stw-operations/taxi-service'
    | '/stw-operations/urns'
    | '/stw-operations/xpboosts'
    | '/accounts/add/$type'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRoute
  AccountManagementDevicesAuthRouteRoute: typeof AccountManagementDevicesAuthRouteRoute
  AccountManagementEpicGamesSettingsRouteRoute: typeof AccountManagementEpicGamesSettingsRouteRoute
  AccountManagementEulaRouteRoute: typeof AccountManagementEulaRouteRoute
  AccountManagementRedeemCodesRouteRoute: typeof AccountManagementRedeemCodesRouteRoute
  AccountManagementVbucksInformationRouteRoute: typeof AccountManagementVbucksInformationRouteRoute
  AccountsRemoveRouteRoute: typeof AccountsRemoveRouteRoute
  AdvancedModeMatchmakingTrackRouteRoute: typeof AdvancedModeMatchmakingTrackRouteRoute
  AdvancedModeWorldInfoRouteRoute: typeof AdvancedModeWorldInfoRouteRoute
  InformationCreditsRouteRoute: typeof InformationCreditsRouteRoute
  StwOperationsAutoLlamasRouteRoute: typeof StwOperationsAutoLlamasRouteRoute
  StwOperationsAutomationRouteRoute: typeof StwOperationsAutomationRouteRoute
  StwOperationsDailyQuestsRouteRoute: typeof StwOperationsDailyQuestsRouteRoute
  StwOperationsPartyRouteRoute: typeof StwOperationsPartyRouteRoute
  StwOperationsTaxiServiceRouteRoute: typeof StwOperationsTaxiServiceRouteRoute
  StwOperationsUrnsRouteRoute: typeof StwOperationsUrnsRouteRoute
  StwOperationsXpboostsRouteRoute: typeof StwOperationsXpboostsRouteRoute
  AccountsAddTypeRoute: typeof AccountsAddTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/xpboosts': {
      id: '/stw-operations/xpboosts'
      path: '/stw-operations/xpboosts'
      fullPath: '/stw-operations/xpboosts'
      preLoaderRoute: typeof StwOperationsXpboostsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/urns': {
      id: '/stw-operations/urns'
      path: '/stw-operations/urns'
      fullPath: '/stw-operations/urns'
      preLoaderRoute: typeof StwOperationsUrnsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/taxi-service': {
      id: '/stw-operations/taxi-service'
      path: '/stw-operations/taxi-service'
      fullPath: '/stw-operations/taxi-service'
      preLoaderRoute: typeof StwOperationsTaxiServiceRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/party': {
      id: '/stw-operations/party'
      path: '/stw-operations/party'
      fullPath: '/stw-operations/party'
      preLoaderRoute: typeof StwOperationsPartyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/daily-quests': {
      id: '/stw-operations/daily-quests'
      path: '/stw-operations/daily-quests'
      fullPath: '/stw-operations/daily-quests'
      preLoaderRoute: typeof StwOperationsDailyQuestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/automation': {
      id: '/stw-operations/automation'
      path: '/stw-operations/automation'
      fullPath: '/stw-operations/automation'
      preLoaderRoute: typeof StwOperationsAutomationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stw-operations/auto-llamas': {
      id: '/stw-operations/auto-llamas'
      path: '/stw-operations/auto-llamas'
      fullPath: '/stw-operations/auto-llamas'
      preLoaderRoute: typeof StwOperationsAutoLlamasRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information/credits': {
      id: '/information/credits'
      path: '/information/credits'
      fullPath: '/information/credits'
      preLoaderRoute: typeof InformationCreditsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-mode/world-info': {
      id: '/advanced-mode/world-info'
      path: '/advanced-mode/world-info'
      fullPath: '/advanced-mode/world-info'
      preLoaderRoute: typeof AdvancedModeWorldInfoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced-mode/matchmaking-track': {
      id: '/advanced-mode/matchmaking-track'
      path: '/advanced-mode/matchmaking-track'
      fullPath: '/advanced-mode/matchmaking-track'
      preLoaderRoute: typeof AdvancedModeMatchmakingTrackRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/remove': {
      id: '/accounts/remove'
      path: '/accounts/remove'
      fullPath: '/accounts/remove'
      preLoaderRoute: typeof AccountsRemoveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-management/vbucks-information': {
      id: '/account-management/vbucks-information'
      path: '/account-management/vbucks-information'
      fullPath: '/account-management/vbucks-information'
      preLoaderRoute: typeof AccountManagementVbucksInformationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-management/redeem-codes': {
      id: '/account-management/redeem-codes'
      path: '/account-management/redeem-codes'
      fullPath: '/account-management/redeem-codes'
      preLoaderRoute: typeof AccountManagementRedeemCodesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-management/eula': {
      id: '/account-management/eula'
      path: '/account-management/eula'
      fullPath: '/account-management/eula'
      preLoaderRoute: typeof AccountManagementEulaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-management/epic-games-settings': {
      id: '/account-management/epic-games-settings'
      path: '/account-management/epic-games-settings'
      fullPath: '/account-management/epic-games-settings'
      preLoaderRoute: typeof AccountManagementEpicGamesSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-management/devices-auth': {
      id: '/account-management/devices-auth'
      path: '/account-management/devices-auth'
      fullPath: '/account-management/devices-auth'
      preLoaderRoute: typeof AccountManagementDevicesAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/add/$type': {
      id: '/accounts/add/$type'
      path: '/accounts/add/$type'
      fullPath: '/accounts/add/$type'
      preLoaderRoute: typeof AccountsAddTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRoute,
  AccountManagementDevicesAuthRouteRoute:
    AccountManagementDevicesAuthRouteRoute,
  AccountManagementEpicGamesSettingsRouteRoute:
    AccountManagementEpicGamesSettingsRouteRoute,
  AccountManagementEulaRouteRoute: AccountManagementEulaRouteRoute,
  AccountManagementRedeemCodesRouteRoute:
    AccountManagementRedeemCodesRouteRoute,
  AccountManagementVbucksInformationRouteRoute:
    AccountManagementVbucksInformationRouteRoute,
  AccountsRemoveRouteRoute: AccountsRemoveRouteRoute,
  AdvancedModeMatchmakingTrackRouteRoute:
    AdvancedModeMatchmakingTrackRouteRoute,
  AdvancedModeWorldInfoRouteRoute: AdvancedModeWorldInfoRouteRoute,
  InformationCreditsRouteRoute: InformationCreditsRouteRoute,
  StwOperationsAutoLlamasRouteRoute: StwOperationsAutoLlamasRouteRoute,
  StwOperationsAutomationRouteRoute: StwOperationsAutomationRouteRoute,
  StwOperationsDailyQuestsRouteRoute: StwOperationsDailyQuestsRouteRoute,
  StwOperationsPartyRouteRoute: StwOperationsPartyRouteRoute,
  StwOperationsTaxiServiceRouteRoute: StwOperationsTaxiServiceRouteRoute,
  StwOperationsUrnsRouteRoute: StwOperationsUrnsRouteRoute,
  StwOperationsXpboostsRouteRoute: StwOperationsXpboostsRouteRoute,
  AccountsAddTypeRoute: AccountsAddTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
